# -*- coding: utf-8 -*-
"""data_salaries.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N-kChQ7aVyjZbrHkKwq94oW2BZeofFVx

Koliko različnih poklicev vsebuje datoteka?

Povprečna plača (v EUR) za vsak poklic?

Primerjaj povprečne plače glede na experience_level (Entry, Mid, Senior).

Kateri poklic ima najvišjo mediano plačo?

Kolikšen delež zaposlitev je remote (remote_ratio == 100)?

Nekaj s čimer bi vadil grafe...
"""

#priprava excela, ki ga prebere z google drive-a
import pandas as pd
from google.colab import drive
drive.mount('/content/drive')
lokacija_excela = '/content/drive/MyDrive/python_projekti/salaries (1).xlsx'
try: #zažene kodo in če koda ne dela, zažene except. Za lovljenje napak
  branje_excela = pd.read_excel(lokacija_excela)  #prebere excel in jo pretvori v tabelo/DataFrame
except FileNotFoundError:
  print('Datoteka ne obstaja')

#KOLIKO RAZLIČNIH POKLICEV VSEBUJE DATOTEKA?
poklici=branje_excela["job_title"].nunique()
print(poklici)

#POVPREČNA PLAČA (V EUR) ZA VSAK POKLIC
#ustvarimo slovar "valuta":"koeficient pretvorbe" za pretvarjanje plač v EUR
slovar_valute = {
    'USD': 0.85,
    'EUR': 1,
    'GBP': 1.16,
    'CAD': 0.62,
    'MXN': 0.046,
    'PLN': 0.24,
    'CHF': 1.07,
    'PHP': 0.015,
    'JPY': 0.0058,
    'INR': 0.0099,
    'SGD': 0.67,
    'HUF': 0.0025,
    'AUD': 0.56,
    'TWD': 0.029,
    'NOK': 0.084,
    'BRL': 0.16,
    'CZK': 0.041,
    'ZAR': 0.048,
    'DKK': 0.13,
    'ILS': 0.25,
    'TRY': 0.021,
    'SEK': 0.09,
    'NZD': 0.51,
    'HKD': 0.11,
    'THB': 0.026,
    'CLP': 0.0009
}

#Uporabi transformacijo "v zraku" (brez dodajanja stolpca)
branje_excela["koeficienti_pretvorbe"] = branje_excela["salary_currency"].map(slovar_valute)
#funkcija .map() vrednosti (valute) iz stolpca "salary_currency" Excela zamenja z vrednostmi iz slovarja;
#npr. USD zamenja z vrednostjo 0,85
branje_excela["salary(EUR)"] = branje_excela["salary"] * branje_excela["koeficienti_pretvorbe"]

# 4. Povprečna plača v EUR po poklicih (brez spreminjanja originalne tabele)
poklici = branje_excela.groupby("job_title")
povprecje=poklici["salary(EUR)"].mean().sort_values(ascending=False)
#branje_excela.groupby("job_title") združi vrstice, ki imajo enako vrednost (poklic)-podobno kot pivot tabela naredi v excelu, naredi le unikatne skupine brez računanja
#z dodajanjem funkcij .mean()=>povprečje, .sum()=>vsota, .count()=>prešteje pa operira mo znotraj teh skupin
#.sort_values(ascending=False) razporedi vrednosti od največje do najmanjše
# 5. Prikaži rezultat vseh poklicev brez shranjevanja v excel
print(povprecje)
#for valuta, koef in povprecje.items():
#    print(f"{valuta} : {koef}")

#PRIMERJAVA POVPREČNE PLAČE GLEDE NA IZKUŠNJE
slovar_group={'Actuarial Analyst': 'Analyst',
 'Admin & Data Analyst': 'Analyst',
 'AI Content Writer': 'AI',
 'AI Data Engineer': 'AI',
 'AI Data Scientist': 'AI',
 'AI Developer': 'AI',
 'AI Engineer': 'AI',
 'AI Machine Learning Engineer': 'AI',
 'AI Programmer': 'AI',
 'AI Research Engineer': 'AI',
 'AI Research Scientist': 'AI',
 'AI Researcher': 'AI',
 'AI Scientist': 'AI',
 'AI Software Engineer': 'AI',
 'AI Specialist': 'AI',
 'Algorithm Developer': 'AI',
 'Alternance': 'Programing',
 'Analyst': 'Analyst',
 'Analytics Engineer': 'Analyst',
 'Analytics Specialist': 'Analyst',
 'Application Developer': 'Programing',
 'Applied Data Scientist': 'Data',
 'Applied Machine Learning Scientist': 'Data',
 'Applied Scientist': 'Data',
 'Architect': 'Architect',
 'Artificial Intelligence Engineer': 'AI',
 'Associate': 'Associate',
 'Azure Data Engineer': 'Data',
 'Bear Robotics': 'AI',
 'BI Analyst': 'Analyst',
 'BI Data Analyst': 'Data',
 'BI Data Engineer': 'Data',
 'BI Developer': 'Programing',
 'BI Engineer': 'Programing',
 'Big Data Engineer': 'Data',
 'Bioinformatician': 'Bioinformatician',
 'Bioinformatics Scientist': 'Bioinformatics Scientist',
 'Business Analyst': 'Business',
 'Business Data Analyst': 'Business',
 'Business Development Representative': 'Business',
 'Business Intelligence': 'Business',
 'Business Intelligence Analyst': 'Business',
 'Business Intelligence Data Analyst': 'Business',
 'Business Intelligence Developer': 'Business',
 'Business Intelligence Engineer': 'Business',
 'Business Intelligence Lead': 'Business',
 'Business Intelligence Specialist': 'Business',
 'Chatbot Developer': 'AI',
 'Cientista de Dados': 'Data',
 'Cloud Data Engineer': 'Data',
 'Cloud Engineer': 'Data',
 'Compliance Data Analyst': 'Data',
 'Computational Scientist': 'Data',
 'Computer Vision Engineer': 'Data',
 'Computer Vision Software Engineer': 'Data',
 'Creative Technologist': 'Data',
 'Data & Analytics Analyst': 'Data',
 'Data Analist': 'Data',
 'Data Analysis': 'Data',
 'Data Analyst': 'Data',
 'Data Analyst Lead': 'Data',
 'Data Analytics Associate': 'Data',
 'Data Analytics Consultant': 'Data',
 'Data Analytics Developer': 'Data',
 'Data Analytics Engineer': 'Data',
 'Data Analytics Lead': 'Data',
 'Data Analytics Manager': 'Data',
 'Data Analytics Specialist': 'Data',
 'Data and Reporting Analyst': 'Data',
 'Data and Reporting Professional': 'Data',
 'Data Architect': 'Data',
 'Data Consultant': 'Data',
 'Data Developer': 'Data',
 'Data DevOps Engineer': 'Data',
 'Data Engineer': 'Data',
 'Data Governance': 'Data',
 'Data Governance Analyst': 'Data',
 'Data Governance Consultant': 'Data',
 'Data Governance Engineer': 'Data',
 'Data Governance Specialist': 'Data',
 'Data Integration Analyst': 'Data',
 'Data Integration Engineer': 'Data',
 'Data Integration Specialist': 'Data',
 'Data Integrity Analyst': 'Data',
 'Data Integrity Specialist': 'Data',
 'Data Management': 'Data',
 'Data Management Analyst': 'Data',
 'Data Management Consultant': 'Data',
 'Data Management Specialist': 'Data',
 'Data Manager': 'Data',
 'Data Operations Analyst': 'Data',
 'Data Operations Associate': 'Data',
 'Data Operations Engineer': 'Data',
 'Data Operations Manager': 'Data',
 'Data Platform Engineer': 'Data',
 'Data Product Analyst': 'Data',
 'Data Product Manager': 'Data',
 'Data Quality Analyst': 'Data',
 'Data Quality Engineer': 'Data',
 'Data Quality Specialist': 'Data',
 'Data Reporting Analyst': 'Data',
 'Data Scientist': 'Data',
 'Data Specialist': 'Data',
 'Data Strategist': 'Data',
 'Data Visualization Analyst': 'Data',
 'Data Visualization Engineer': 'Data',
 'Data Visualization Specialist': 'Data',
 'Deep Learning Engineer': 'AI',
 'Developer': 'Programing',
 'DevOps Engineer': 'Programing',
 'Director': 'Director',
 'Encounter Data Management Professional': 'Data',
 'Engineer': 'Programing',
 'Engineering Manager': 'Manager',
 'ETL Developer': 'Programing',
 'Finance Data Analyst': 'Data',
 'Financial Data Analyst': 'Data',
 'Fraud Data Analyst': 'Data',
 'Full Stack Developer': 'Programing',
 'Full Stack Engineer': 'Programing',
 'Head of Data': 'Data',
 'Insight Analyst': 'Analyst',
 'Machine Learning Developer': 'AI',
 'Machine Learning Engineer': 'AI',
 'Machine Learning Model Engineer': 'AI',
 'Machine Learning Research Engineer': 'AI',
 'Machine Learning Researcher': 'AI',
 'Machine Learning Scientist': 'AI',
 'Machine Learning Specialist': 'AI',
 'Manager': 'Manager',
 'Marketing Data Engineer': 'Data',
 'Master Data Management': 'Data',
 'ML Scientist': 'Data',
 'MLOps Engineer': 'Programing',
 'Platform Engineer': 'Programing',
 'Postdoctoral Fellow': 'Research',
 'Postdoctoral Researcher': 'Research',
 'Power BI': 'Programing',
 'Power BI Developer': 'Programing',
 'Pricing Analyst': 'Data',
 'Product Analyst': 'Data',
 'Product Data Analyst': 'Data',
 'Product Designer': 'Data',
 'Product Manager': 'Data',
 'Prompt Engineer': 'Programing',
 'Python Developer': 'Programing',
 'Quant Trader': 'Business',
 'Quantitative Analyst': 'Analyst',
 'Quantitative Developer': 'Research',
 'Quantitative Research Analyst': 'Research',
 'Quantitative Researcher': 'Research',
 'Research Analyst': 'Research',
 'Research Assistant': 'Research',
 'Research Associate': 'Research',
 'Research Engineer': 'Research',
 'Research Scientist': 'Research',
 'Researcher': 'Research',
 'Risk Analyst': 'Analyst',
 'Robotics Engineer': 'AI',
 'Sales Development Representative': 'Business',
 'Site Reliability Engineer': 'Programing',
 'Software Architect': 'Programing',
 'Software Developer': 'Programing',
 'Software Development Engineer': 'Programing',
 'Software Engineer': 'Programing',
 'Solution Architect': 'Programing',
 'Solutions Architect': 'Programing',
 'Solutions Engineer': 'Programing',
 'Staff Data Analyst': 'Data',
 'Stage': 'Stage',
 'Statistical Programmer': 'Statistical Programmer',
 'Statistician': 'Statistician',
 'System Engineer': 'Programing',
 'Systems Administrator': 'Programing',
 'Systems Engineer': 'Programing',
 'Technical Specialist': 'Technical Specialist',
 'Technical Writer': 'Technical Writer',
 'Trainee': 'Trainee',
 'Web Developer': 'Programing',
 'Account Executive': 'Other',
 'Actuary': 'Other',
 'AI Architect': 'Other',
 'AI Tech Lead': 'Other',
 'Applied Machine Learning Engineer': 'Other',
 'Backend Engineer': 'Other',
 'Consultant': 'Consultant',
 'Data Governance Manager': 'Other',
 'Data Lead': 'Other',
 'Data Management Lead': 'Other',
 'Data Operations': 'Other',
 'Data Operations Specialist': 'Other',
 'Data Product Owner': 'Other',
 'Data Visualization Designer': 'Other',
 'Decision Scientist': 'Other',
 'Director of Business Intelligence': 'Other',
 'Director of Data': 'Other',
 'Director of Machine Learning': 'Other',
 'Director of Product Management': 'Other',
 'Enterprise Account Executive': 'Other',
 'ETL Engineer': 'Other',
 'Executive': 'Other',
 'Head of AI': 'Other',
 'Head of Applied AI': 'Other',
 'Head of Business Intelligence': 'Other',
 'Head of Machine Learning': 'Other',
 'Head of Marketing': 'Other',
 'Lead Data Engineer': 'Other',
 'NLP Engineer': 'Other',
 'People Data Analyst': 'Other',
 'Postdoctoral Research Fellow': 'Other',
 'Principal Data Scientist': 'Other',
 'Product Owner': 'Other',
 'Quant Options Trader': 'Other',
 'Robotics Software Engineer': 'Other',
 'Software Development Director': 'Other',
 'Solution Engineer': 'Other',
 'Technical Lead': 'Other',
 'MI': 'Other',
 'AI Governance Specialist': 'Other',
 'AI Lead': 'Other',
 'AI Product Manager': 'Other',
 'AI Product Owner': 'Other',
 'AI Solutions Specialist': 'Other',
 'Analytics Analyst': 'Other',
 'Analytics Manager': 'Other',
 'Applied Research Scientist': 'Other',
 'Automation Engineer': 'Other',
 'Autonomous Vehicle Technician': 'Other',
 'AWS Data Architect': 'Other',
 'Backend Developer': 'Other',
 'Backend Software Engineer': 'Other',
 'BI & Data Analyst': 'Other',
 'Big Data Analyst': 'Other',
 'Big Data Developer': 'Other',
 'Bioinformatics Specialist': 'Other',
 'Business Development Manager': 'Other',
 'Business Insights Manager': 'Other',
 'Business Intelligence Manager': 'Other',
 'Cheminformatics Scientist': 'Other',
 'Clinical Aide': 'Other',
 'Clinical Data Operator': 'Other',
 'Cloud Database Administrator': 'Other',
 'Cloud Database Engineer': 'Other',
 'Cloud Developer': 'Other',
 'Computational Biologist': 'Other',
 'Conversational AI Designer': 'Other',
 'Copywriter': 'Other',
 'Customer Success Engineer': 'Other',
 'Customer Success Manager': 'Other',
 'Data Analysis Specialist': 'Other',
 'Data Analytics Business Partner': 'Other',
 'Data and Analytics Consultant': 'Other',
 'Data Archivist': 'Other',
 'Data Governance Lead': 'Other',
 'Data Infrastructure Engineer': 'Other',
 'Data Integration Coordinator': 'Other',
 'Data Integration Developer': 'Other',
 'Data Integrator': 'Other',
 'Data Management Associate': 'Other',
 'Data Management Manager': 'Other',
 'Data Modeler': 'Other',
 'Data Operator': 'Other',
 'Data Quality Manager': 'Other',
 'Data Reporter': 'Other',
 'Data Reporting Specialist': 'Other',
 'Data Scientist Associate': 'Other',
 'Data Scientist Lead': 'Other',
 'Data Steward': 'Other',
 'Data Strategy Manager': 'Other',
 'Data Visualization Developer': 'Other',
 'Database Administrator': 'Other',
 'DataOps Engineer': 'Other',
 'Developer Advocate': 'Other',
 'Frontend Engineer': 'Other',
 'Fullstack Engineer': 'Other',
 'Integration Specialist': 'Other',
 'Java Developer': 'Other',
 'Lead Data Analyst': 'Other',
 'Lead Data Scientist': 'Other',
 'Machine Learning Infrastructure Engineer': 'Other',
 'Machine Learning Manager': 'Other',
 'Machine Learning Platform Engineer': 'Other',
 'Machine Learning Quality Engineer': 'Other',
 'Machine Learning Software Engineer': 'Other',
 'Machine Vision Engineer': 'Other',
 'Marketing Analytics Manager': 'Other',
 'Marketing Science Partner': 'Other',
 'Master Data Specialist': 'Other',
 'ML Infrastructure Engineer': 'Other',
 'Network Engineer': 'Other',
 'Platform Data Engineer': 'Other',
 'Power BI Administrator': 'Other',
 'Power BI Specialist': 'Other',
 'Principal Data Analyst': 'Other',
 'Principal Statistical Programmer': 'Other',
 'Product Specialist': 'Other',
 'Psychometrician': 'Other',
 'QA Engineer': 'Other',
 'Quantitative Trader': 'Other',
 'Research Data Manager': 'Other',
 'Research Professional': 'Other',
 'RPA Developer': 'Other',
 'Sales Data Analyst': 'Other',
 'Sales Engineer': 'Other',
 'Salesforce Administrator': 'Other',
 'Scala Spark Developer': 'Other',
 'Security Engineer': 'Other',
 'Security Researcher': 'Other',
 'Software Data Engineer': 'Other',
 'System Administrator': 'Other',
 'Tableau Developer': 'Other',
 'Technical Recruiter': 'Other',
 'Technical Support Engineer': 'Other',
 'Technical Support Specialist': 'Other',
 'Technology Integrator': 'Other',
 'SE': 'Other',
 'Advanced Data Analyst': 'Other',
 'AI Engineering Lead': 'Other',
 'AI Engineering Manager': 'Other',
 'AI Governance Lead': 'Other',
 'AI Product Lead': 'Other',
 'AI Software Development Engineer': 'Other',
 'AI Solution Architect': 'Other',
 'AI Solutions Lead': 'Other',
 'AI Strategist': 'Other',
 'Analytics Engineering Manager': 'Other',
 'Analytics Lead': 'Other',
 'Applied AI ML Lead': 'Other',
 'Big Data Architect': 'Other',
 'Business Intelligence Consultant': 'Other',
 'Cloud Architect': 'Other',
 'Cloud Data Architect': 'Other',
 'Consultant Data Engineer': 'Other',
 'Controls Engineer': 'Other',
 'CRM Data Analyst': 'Other',
 'Data Analytics Team Lead': 'Other',
 'Data Engineer 4': 'Other',
 'Data Governance Architect': 'Other',
 'Data Integration Lead': 'Other',
 'Data Management Coordinator': 'Other',
 'Data Management Expert': 'Other',
 'Data Operations Lead': 'Other',
 'Data Pipeline Engineer': 'Other',
 'Data Product Lead': 'Other',
 'Data Quality Expert': 'Other',
 'Data Quality Lead': 'Other',
 'Data Science Tech Lead': 'Other',
 'Data Scientist Expert': 'Other',
 'Data Scientist Manager': 'Other',
 'Data Strategy Lead': 'Other',
 'Data Team Lead': 'Other',
 'Data Visualization Expert': 'Other',
 'Data Visualization Lead': 'Other',
 'Databricks Engineer': 'Other',
 'Deep Learning Researcher': 'Other',
 'DevOps Lead': 'Other',
 'Economist': 'Other',
 'Elasticsearch Administrator': 'Other',
 'Experienced Quantitative Strategist': 'Other',
 'GenAI Architect': 'Other',
 'Infrastructure Engineer': 'Other',
 'IT Enterprise Data Architect': 'Other',
 'Lead AI Engineer': 'Other',
 'Lead Analyst': 'Other',
 'Lead Data Analysis': 'Other',
 'Lead Data Management': 'Other',
 'Lead Engineer': 'Other',
 'Lead Machine Learning Engineer': 'Other',
 'LLM Engineer': 'Other',
 'Machine Learning Architect': 'Other',
 'Machine Learning Lead': 'Other',
 'Machine Learning Modeler': 'Other',
 'Machine Learning Performance Engineer': 'Other',
 'Machine Learning Tech Lead': 'Other',
 'Manager Data Management': 'Other',
 'Marketing Analyst': 'Other',
 'Marketing Data Analyst': 'Other',
 'Marketing Data Scientist': 'Other',
 'Member of Technical Staff': 'Other',
 'Post Doctoral Fellow': 'Other',
 'Power BI Architect': 'Other',
 'Power BI Consultant': 'Other',
 'Power BI Expert': 'Other',
 'Principal Application Delivery Consultant': 'Other',
 'Principal Data Architect': 'Other',
 'Principal Data Engineer': 'Other',
 'Principal Engineer': 'Other',
 'Principal Machine Learning Engineer': 'Other',
 'Principal Researcher': 'Other',
 'Principal Scientist': 'Other',
 'Principal Software Architect': 'Other',
 'Research Team Lead': 'Other',
 'Safety Data Management Specialist': 'Other',
 'SAS Developer': 'Other',
  'Staff Data Scientist': 'Other',
  'Staff Engineer': 'Other',
  'Staff Machine Learning Engineer': 'Other',
  'Tech Lead': 'Other','Tech Lead Data': 'Other','Technical Architect': 'Other','Grand Total': 'Total'}

#slovar=dict(zip(branje_excela["job_title"], (branje_analize["experience_level"],slovar_group[branje_excela["job_title"]] )))
#print(slovar)

slovar = {
    index: [row["job_title"], row["experience_level"], row["salary(EUR)"]]
    for index, row in branje_excela.iterrows()
}

print(slovar)

for element in slovar:
    poklic = slovar[element][0]
    if poklic in slovar_group:
        nova_vrednost = [slovar_group[poklic], slovar[element][1], slovar[element][2]]
        slovar[element] = nova_vrednost
print(slovar)

slovar_plač = {}
#s pomočjo množenja s praštevilom sem preko matematičnih operacij naredil unikaten način štetja sprememb plač, vendar za moj primer ni praktičen zaradi previsokega števila vnosov
for ključ in slovar:
    skupina = slovar[ključ][0]
    izkusnje = slovar[ključ][1]
    plača = float(slovar[ključ][2])

    if izkusnje not in slovar_plač:
        slovar_plač[izkusnje] = {}
        notranji_slovar= slovar_plač[izkusnje]
    else:
        if skupina not in notranji_slovar:
          notranji_slovar[skupina]=plača
        else:
          notranji_slovar[skupina]=(notranji_slovar[skupina] * 11) + plača
def kompliciranje(stevilka):
    stevec = 1
    while stevilka % 11 == 0:
        stevilka /= 11
        stevec += 1
    return stevec
for poklic in notranji_slovar:
    st = kompliciranje(notranji_slovar[poklic])
    povprecje = notranji_slovar[poklic] / st
    notranji_slovar[poklic] = povprecje
for ključ in slovar_plač:
  print(notranji_slovar)

"""
slovar_plač = {}
stevilo=1
vsota_plač=0
#s pomočjo seznama znotraj slovarja bom izračunal povprečje
for ključ in slovar:
    skupina = slovar[ključ][0]
    izkusnje = slovar[ključ][1]
    plača = float(slovar[ključ][2])

    if izkusnje not in slovar_plač:
        slovar_plač[izkusnje] = {}
        notranji_slovar= slovar_plač[izkusnje]
    else:
        seznam=(vsota_plač,stevilo)
        if skupina not in notranji_slovar:
          vsota_plač=plača
          notranji_slovar[skupina]=seznam
        else:
          stevilo=stevilo + 1
          vsota_plač=vsota_plač+plača
          nov_seznam=(vsota_plač,stevilo)
          notranji_slovar[skupina]=nov_seznam
for skupina in notranji_slovar:
  povprecje=notranji_slovar[skupina][0]/notranji_slovar[skupina][1]
  notranji_slovar[skupina]=povprecje

print(slovar_plač)
"""

slovar_plač = {}  # 🟢 1. Popravek: začetni slovar ostane

for ključ in slovar:
    skupina = slovar[ključ][0]
    izkusnje = slovar[ključ][1]
    plača = float(slovar[ključ][2])

    if izkusnje not in slovar_plač:
        slovar_plač[izkusnje] = {}  # 🟢 2. Popravek: ustvari notranji slovar za vsako izkušnjo
    notranji_slovar = slovar_plač[izkusnje]  # 🟢 3. Premik skupnega dostopa – bolj pregledno
    if skupina not in notranji_slovar:
        notranji_slovar[skupina] = [plača, 1]  # ✅ 4. Shranimo seznam: [vsota_plač, števec]
    else:
        notranji_slovar[skupina][0] += plača   # ✅ 5. Dodajamo na obstoječo vsoto
        notranji_slovar[skupina][1] += 1       # ✅ 6. Povečamo števec
"""
# ✅ 7. Izračun povprečja – ločeno, po zaključku zbiranja podatkov
for izkusnje in slovar_plač:
    for skupina in slovar_plač[izkusnje]:
        vsota = slovar_plač[izkusnje][skupina][0]
        st = slovar_plač[izkusnje][skupina][1]
        povprecje = vsota / st
        slovar_plač[izkusnje][skupina] = round(povprecje, 0)  # 🔄 zamenjamo seznam s povprečjem
"""
print(slovar_plač)

vrstice = []
for izkusnje, podslovar in slovar_plač.items():
    for poklic, povprecje in podslovar.items():
        vrstice.append({"grouping": poklic, "experience_level": izkusnje, "avg_salary": povprecje})
df = pd.DataFrame(vrstice)
pivot_df = df.pivot(index="grouping", columns="experience_level", values="avg_salary")
print(pivot_df)

import matplotlib.pyplot as plt
import numpy as np
vsi_poklici = set()
for nivo in slovar_plač.values():
    vsi_poklici.update(nivo.keys())
poklici = sorted(list(vsi_poklici))
število_poklicev = len(poklici)
širina_stolpca = 0.2
x = np.arange(število_poklicev)

plt.figure(figsize=(19.5, 6))

for i, nivo in enumerate(slovar_plač.keys()):
    place = [slovar_plač[nivo].get(poklic, 0) for poklic in poklici]
    plt.bar(x + i * širina_stolpca, place, width=širina_stolpca, label=nivo)

plt.xticks(x + širina_stolpca * (len(slovar_plač)-1)/2, poklici, rotation=45)
plt.xlabel('Grouped title')
plt.ylabel('Average salary [€]')
plt.title('Average salary[€] correlating to experience level')
plt.legend(title='Experience level')
plt.tight_layout()
plt.show()

#Kateri poklic ima najvišjo mediano plačo?
slovar = {
    index: (row["job_title"], row["experience_level"], row["salary_in_usd"])
    for index, row in branje_excela.iterrows()
}
print(slovar)

slovar_mediana = {}
poskus=[1,5,2,4]
poskus2=[9,6,2,6,4]
for kljuc in slovar:
    poklic = slovar[kljuc][0]
    nivo = slovar[kljuc][1]
    placa = slovar[kljuc][2]

    # Inicializacija gnezdene strukture
    if nivo not in slovar_mediana:
        slovar_mediana[nivo] = {}
    else:
        gnezdo=slovar_mediana[nivo]
        if poklic not in gnezdo:
          gnezdo[poklic]=[placa]
        else:
          gnezdo[poklic].append(placa)
#funkcija iskanje_mediane vzame seznam, ga razvrsti in vrne mediano
def iskanje_mediane(vnos):
    razporejen_seznam = sorted(vnos)
    n = len(razporejen_seznam)

    if n == 0:
        return "Ni mediane"
    if n % 2 == 0:
        sredina = n // 2 #// je celoštevilsko deljenje, deli in nato zaokroži navzdol
                         #npr. 9//2=4, zato dobimo int
        mediana = (razporejen_seznam[sredina - 1] + razporejen_seznam[sredina]) / 2
        return mediana
    else:
        sredina = n // 2
        return razporejen_seznam[sredina]

print(slovar_mediana)

for element in slovar_mediana:
  for poklic in slovar_mediana[element]:
    iskanje=slovar_mediana[element][poklic]
    mediana=iskanje_mediane(iskanje)
    slovar_mediana[element][poklic]=mediana
df = pd.DataFrame.from_dict(slovar_mediana, orient='columns')
df = df.transpose()  # če želiš, da nivoji izkušenj postanejo vrstice

# Ampak za tvojo željo: vrstice = poklici, stolpci = nivoji
df = pd.DataFrame.from_dict(slovar_mediana, orient='index')  # nivoji postanejo vrstice
df = df.transpose()  # poklici postanejo vrstice
print(df)
print(slovar_mediana)

slovar_mm={}
def max_mediana(dictionary):
  for element in dictionary:
    maksimum=0
    notranji_slovar=dictionary[element]
    #if element not in slovar_mm:
     # slovar_mm[element]=dictionary[element]
    for poklic in notranji_slovar:
      if notranji_slovar[poklic]>maksimum:
        maksimum=notranji_slovar[poklic]
    slovar_mm.update({element:{poklic:maksimum}})
  return slovar_mm
pprint(max_mediana(slovar_mediana))

#Kolikšen delež grupiranih poklicev je na daljavo? In kakšna je povprečna plača za tiste na daljavo?
slovar1 = {
    index: [row["job_title"], row["remote_ratio"], row["salary(EUR)"]]
    for index, row in branje_excela.iterrows()
}
for element in slovar1:
    poklic = slovar1[element][0]
    if poklic in slovar_group:
        nova_vrednost = [slovar_group[poklic], slovar1[element][1], slovar1[element][2]]
        slovar1[element] = nova_vrednost

print(slovar1)

slovar2 = {}
"""
for element in slovar1:
    poklic = str(slovar1[element][0])
    delez = int(slovar1[element][1])
    placa = float(slovar1[element][2])

    if poklic not in slovar2:
        notranji_slovar={}
        slovar2[poklic] = notranji_slovar
        notranji_slovar[delez]=[placa,1]
    else:
      if delez == slovar2[element]:
        slovar2[element][notranji_slovar][0]=slovar2[element][notranji_slovar][0] + placa
        slovar2[element][notranji_slovar][1]=slovar2[element][notranji_slovar][1] + 1
        notranji_slovar.update({delez:[nova_placa, nov_stevec]})
      else:
        notranji_slovar.update({delez:[placa, 1]})

"""
slovar2 = {}

for element in slovar1.values():
    poklic = str(element[0])
    delež = int(element[1])
    plača = float(element[2])

    # Če poklic še ni v slovarju, ga dodamo
    if poklic not in slovar2:
        slovar2[poklic] = {delež: [plača, 1]}  # notranji slovar
    else:
        notranji_slovar = slovar2[poklic]

        # Če ta delež že obstaja → posodobi
        if delež in notranji_slovar:
            notranji_slovar[delež][0] += plača
            notranji_slovar[delež][1] += 1
        else:
            # drugače dodaj nov delež
            notranji_slovar[delež] = [plača, 1]

print(slovar2)

# Funkcija za izračun skupnega števila zaposlenih za določen poklic
def vsi_poklici(vnesen_slovar):
    vsota = 0
    for nek in vnesen_slovar:
        vsota += vnesen_slovar[nek][1]  # [1] je števec (število ljudi)
    return vsota

# slovar2 je predhodno napolnjen v obliki:
# {'Analyst': {0: [skupna_plača, št_ljudi], 100: [skupna_plača, št_ljudi]}, ...}

slovar3 = {}  # tukaj bomo zapisali rezultate

for poklic in slovar2:
    notranji = slovar2[poklic]                   # dobimo slovar deležev za ta poklic
    skupno = vsi_poklici(notranji)               # koliko ljudi je skupaj v tem poklicu
    slovar3[poklic] = {}                         # pripravimo prazen notranji slovar

    for delež in notranji:
        vsota_plac = notranji[delež][0]          # skupna plača za ta delež
        število_ljudi = notranji[delež][1]       # koliko ljudi je v tem deležu

        povprečje = vsota_plac / število_ljudi
        relativni_delež = (število_ljudi / skupno) * 100

        slovar3[poklic][delež] = [povprečje, relativni_delež]

# Uporabimo pprint za boljši izpis
from pprint import pprint
pprint(slovar3)

import matplotlib.pyplot as plt
import numpy as np

# Ključi poklicev in kategorije dela na daljavo
poklici = list(slovar3.keys())
kategorije = [0, 50, 100]

# Pripravimo y-vrednosti za vsako kategorijo (deleži v %)
y_vrednosti = {k: [] for k in kategorije}

for poklic in poklici:
    notranji = slovar3[poklic]
    for k in kategorije:
        if k in notranji:
            y_vrednosti[k].append(notranji[k][1])  # delež (%)
        else:
            y_vrednosti[k].append(0)  # če manjka, nastavi na 0

# Nastavitve stolpcev
širina = 0.25
x = np.arange(len(poklici))

plt.figure(figsize=(14, 6))
plt.bar(x - širina, y_vrednosti[0], width=širina, label='0% Remote')
plt.bar(x, y_vrednosti[50], width=širina, label='50% Remote')
plt.bar(x + širina, y_vrednosti[100], width=širina, label='100% Remote')

# Označimo osi
plt.xticks(x, poklici, rotation=45, ha='right')
plt.ylabel('Percentage [%]')
plt.title('Percentage of remote work per grouped title')
plt.legend()
plt.tight_layout()
plt.grid(axis='y', linestyle='--', alpha=0.5)
plt.show()